export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";

export const GET_PROJECTIMAGES = "GET_PROJECTIMAGES";
export const GET_PROJECTIMAGE = "GET_PROJECTIMAGE";
export const ADD_PROJECTIMAGE = "ADD_PROJECTIMAGE";
export const DELETE_PROJECTIMAGE = "DELETE_PROJECTIMAGE";
export const PROJECTIMAGE_LOADING = "PROJECTIMAGE_LOADING";

export const GET_ANNOTATIONS = "GET_ANNOTATIONS";
export const GET_ANNOTATION = "GET_ANNOTATION";
export const ADD_ANNOTATION = "ADD_ANNOTATION";
export const DELETE_ANNOTATION = "DELETE_ANNOTATION";
export const ANNOTATION_LOADING = "ANNOTATION_LOADING ";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
